### ISSUE TITLE
how to train dcgan on another dataset

### ISSUE THREAD

**Issue by kaakboom** [AshishBora/csgm#3]
Hi Ashish

I'm wondering how to train the dcgan on another dataset? I have tried using code from https://github.com/carpedm20/DCGAN-tensorflow to train the model and then directly use it in this project but it doesn't work

**Comment by AshishBora** [comment]
Do you get an error? If yes, can you post it here?

**Comment by kaakboom** [comment]
It shows this:


2018-02-13 18:35:43.186249: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_bn0/gamma not found in checkpoint
2018-02-13 18:35:43.196806: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_bn0/moving_mean not found in checkpoint
2018-02-13 18:35:43.197912: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_bn1/gamma not found in checkpoint
2018-02-13 18:35:43.197912: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_bn1/beta not found in checkpoint
2018-02-13 18:35:43.202785: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_bn2/moving_mean not found in checkpoint
2018-02-13 18:35:43.202947: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_bn1/moving_variance not found in checkpoint
2018-02-13 18:35:43.203474: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_bn2/moving_variance not found in checkpoint
2018-02-13 18:35:43.203632: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_bn1/moving_mean not found in checkpoint
2018-02-13 18:35:43.204166: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_bn3/beta not found in checkpoint
2018-02-13 18:35:43.205619: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_bn2/beta not found in checkpoint
2018-02-13 18:35:43.206940: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_h2/biases not found in checkpoint
2018-02-13 18:35:43.208176: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_h3/biases not found in checkpoint
2018-02-13 18:35:43.208300: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_h1/w not found in checkpoint
2018-02-13 18:35:43.208475: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_h0_lin/Matrix not found in checkpoint
2018-02-13 18:35:43.208659: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_bn0/moving_variance not found in checkpoint
2018-02-13 18:35:43.209020: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_h1/biases not found in checkpoint
2018-02-13 18:35:43.209233: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_bn0/beta not found in checkpoint
2018-02-13 18:35:43.209519: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_bn2/gamma not found in checkpoint
2018-02-13 18:35:43.209847: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_bn3/gamma not found in checkpoint
2018-02-13 18:35:43.210525: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_h3/w not found in checkpoint
2018-02-13 18:35:43.210721: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_h2/w not found in checkpoint
2018-02-13 18:35:43.210730: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_h0_lin/bias not found in checkpoint
2018-02-13 18:35:43.210842: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_bn3/moving_mean not found in checkpoint
2018-02-13 18:35:43.210942: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_bn3/moving_variance not found in checkpoint
2018-02-13 18:35:43.211142: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_h4/biases not found in checkpoint
2018-02-13 18:35:43.211211: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key g_h4/w not found in checkpoint
Traceback (most recent call last):
  File "./src/compressed_sensing.py", line 177, in <module>
    main(HPARAMS)
  File "./src/compressed_sensing.py", line 21, in main
    estimators = utils.get_estimators(hparams)
  File "/home/user/zzhan362/PycharmProjects/201712/csgm/src/utils.py", line 98, in get_estimators
    estimators = {model_type: get_estimator(hparams, model_type) for model_type in hparams.model_types}
  File "/home/user/zzhan362/PycharmProjects/201712/csgm/src/utils.py", line 98, in <dictcomp>
    estimators = {model_type: get_estimator(hparams, model_type) for model_type in hparams.model_types}
  File "/home/user/zzhan362/PycharmProjects/201712/csgm/src/utils.py", line 91, in get_estimator
    estimator = celebA_estimators.dcgan_estimator(hparams)
  File "/home/user/zzhan362/PycharmProjects/201712/csgm/src/celebA_estimators.py", line 192, in dcgan_estimator
    restorer_gen.restore(sess, restore_path_gen)
  File "/home/user/zzhan362/miniconda2/envs/csgm/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/user/zzhan362/miniconda2/envs/csgm/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/user/zzhan362/miniconda2/envs/csgm/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/user/zzhan362/miniconda2/envs/csgm/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/user/zzhan362/miniconda2/envs/csgm/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key g_bn0/gamma not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
	 [[Node: save/RestoreV2_15/_9 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_60_save/RestoreV2_15", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op u'save/RestoreV2_1', defined at:
  File "./src/compressed_sensing.py", line 177, in <module>
    main(HPARAMS)
  File "./src/compressed_sensing.py", line 21, in main
    estimators = utils.get_estimators(hparams)
  File "/home/user/zzhan362/PycharmProjects/201712/csgm/src/utils.py", line 98, in get_estimators
    estimators = {model_type: get_estimator(hparams, model_type) for model_type in hparams.model_types}
  File "/home/user/zzhan362/PycharmProjects/201712/csgm/src/utils.py", line 98, in <dictcomp>
    estimators = {model_type: get_estimator(hparams, model_type) for model_type in hparams.model_types}
  File "/home/user/zzhan362/PycharmProjects/201712/csgm/src/utils.py", line 91, in get_estimator
    estimator = celebA_estimators.dcgan_estimator(hparams)
  File "/home/user/zzhan362/PycharmProjects/201712/csgm/src/celebA_estimators.py", line 190, in dcgan_estimator
    restorer_gen = tf.train.Saver(var_list=restore_dict_gen)
  File "/home/user/zzhan362/miniconda2/envs/csgm/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/home/user/zzhan362/miniconda2/envs/csgm/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/user/zzhan362/miniconda2/envs/csgm/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/user/zzhan362/miniconda2/envs/csgm/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/home/user/zzhan362/miniconda2/envs/csgm/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/user/zzhan362/miniconda2/envs/csgm/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/user/zzhan362/miniconda2/envs/csgm/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/user/zzhan362/miniconda2/envs/csgm/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/user/zzhan362/miniconda2/envs/csgm/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/user/zzhan362/miniconda2/envs/csgm/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key g_bn0/gamma not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
	 [[Node: save/RestoreV2_15/_9 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_60_save/RestoreV2_15", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]


It seems that some of the variables defined in this project do not exist in the original model.

**Comment by AshishBora** [comment]
Have you tried to print the variable names from your checkpoint (say using [inspect_checkpoint](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/inspect_checkpoint.py)) and changing [these](https://github.com/AshishBora/csgm/blob/master/celebA_dcgan/model_def.py#L119) [functions](https://github.com/AshishBora/csgm/blob/master/celebA_dcgan/model_def.py#L88) accordingly?

**Comment by AshishBora** [comment]
I think the only change is to add `generator/` or `discriminator/` before each variable name.

**Comment by kaakboom** [comment]
sorry, I still don't understand how to modify it. I didn't modify anything of the DCGAN-tensorflow project, just followed these instructions

> Or, you can use your own dataset (without central crop) by:

> $ mkdir data/DATASET_NAME
>... add images to data/DATASET_NAME ...
> $ python main.py --dataset DATASET_NAME --train
> $ python main.py --dataset DATASET_NAME
> $ # example
> $ python main.py --dataset=eyes --input_fname_pattern="*_cropped.png" --train

what should I do next?

**Comment by AshishBora** [comment]
In this [file](https://github.com/AshishBora/csgm/blob/master/celebA_dcgan/model_def.py):
- Add this between line 114 and 115
     ```restore_vars = ['generator/' + restore_var for restore_var in restore_vars]```
- Add this between line 141 and 142
    ```restore_vars = ['discriminator/' + restore_var for restore_var in restore_vars]```

**Comment by kaakboom** [comment]
Hi, Ashish, it does solve the problem. But now there is another error occur:

Traceback (most recent call last):
  File "./src/compressed_sensing.py", line 177, in <module>
    main(HPARAMS)
  File "./src/compressed_sensing.py", line 21, in main
    estimators = utils.get_estimators(hparams)
  File "/home/user/zzhan362/PycharmProjects/201712/csgm/src/utils.py", line 98, in get_estimators
    estimators = {model_type: get_estimator(hparams, model_type) for model_type in hparams.model_types}
  File "/home/user/zzhan362/PycharmProjects/201712/csgm/src/utils.py", line 98, in <dictcomp>
    estimators = {model_type: get_estimator(hparams, model_type) for model_type in hparams.model_types}
  File "/home/user/zzhan362/PycharmProjects/201712/csgm/src/utils.py", line 91, in get_estimator
    estimator = celebA_estimators.dcgan_estimator(hparams)
  File "/home/user/zzhan362/PycharmProjects/201712/csgm/src/celebA_estimators.py", line 190, in dcgan_estimator
    restorer_gen = tf.train.Saver(var_list=restore_dict_gen)
  File "/home/user/zzhan362/miniconda2/envs/csgm/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/home/user/zzhan362/miniconda2/envs/csgm/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/user/zzhan362/miniconda2/envs/csgm/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1251, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save

**Comment by AshishBora** [comment]
This [line](https://github.com/AshishBora/csgm/blob/master/src/celebA_model_def.py#L51) creates a mapping dictionary assuming the variable names in the checkpoint are the same as the model definition. Try to modify it so that the variables map to their names in the checkpoint. A similar modification will be needed for the discriminator.

**Comment by eshalev4** [comment]
Hi Ashish,

I am also trying to use the code for a custom data-set. If I am following your code correctly, I need to manually add a specific entry in many if/elif statements if I am not using specifically either celecA/mnist. Did you intend to support custom data-sets and I am missing something or do I need to manually implement my own code for a custom dataset?

**Comment by AshishBora** [comment]
Hi,

Yes, there are a few things specific to each dataset. This includes getting the input, viewing and saving images, etc. Some estimators are also tailored to specific datasets. This design is intentional to keep core code for compressed sensing independent of where the data comes from or how best to visualize it.

For a custom dataset, the missing functionality will have to implemented. If you are working with images (note that the core compressed sensing code does not need this to be true), you should be able to reuse a lot of code for celebA.

**Comment by eshalev4** [comment]
Hi,

Thanks, I will implement this. I am also working on CS :). Indeed I can reuse much of the celebA code. Just wanted to make sure I am not missing anything.

**Comment by Alex-adim** [comment]
Hi from me also,
note that you will need a trained generative model for the type of data you
are trying to recover. Our current model recovers human faces using DCGAN.
If you can train a generative model for the images you want to recover, our
method will work well. But first you should test your generative model to
see if the data it generates look like the things you are trying to
recover.

If you cannot make a generative model work for your data, you can consider
to update the weights of the GAN during recovery to explain the
measurements also. This is done in our recent paper
https://arxiv.org/abs/1806.06438
where we do not have a trained GAN for tomogaphy or retinopathy images. But
we need more measurements.

hope this helps. Also it was not clear from your email where you work,
which university etc.

best
-Alex

**Comment by eshalev4** [comment]
Hi Alex,

Thanks for the tips, I am training a GAN for my data. I am with the Technion Institute of technology.
