### ISSUE TITLE
Error in the code

### ISSUE THREAD

**Issue by kobepejanash** [AshishBora/csgm#9]
here is the problem, when I run the demos, each returns 
Traceback (most recent call last):
  File "./src/compressed_sensing.py", line 177, in <module>
    main(HPARAMS)
  File "./src/compressed_sensing.py", line 19, in main
    xs_dict = model_input(hparams)
  File "/home/feiht/csgm/src/mnist_input.py", line 56, in model_input
    mnist = input_data.read_data_sets('./data/mnist', one_hot=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 306, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 262, in read_data_sets
    train_images = extract_images(f)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 306, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 62, in extract_images
    magic = _read32(bytestream)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 43, in _read32
    return numpy.frombuffer(bytestream.read(4), dtype=dt)[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

why is it, thank you!

**Comment by AshishBora** [comment]
Did you download the dataset?

**Comment by Gamkiu** [comment]
Dear author , when I run the instruction`./quick_scripts/mnist_reconstr.sh`,I was also got the error like this ,how to solve it? Thank you very much!!

(/home/gamkiu/anaconda3/envs/test) gamkiu@ubuntu:~/csgm$ ./quick_scripts/mnist_reconstr.sh

batch_size = 10
checkpoint_iter = 1
dataset = mnist
decay_lr = False
dloss1_weight = 0.0
dloss2_weight = 0.0
gif = False
gif_dir = 
gif_iter = 1
image_matrix = 1
image_shape = (28, 28, 1)
inpaint_size = 1
input_path_pattern = ./data/celebAtest/*.jpg
input_type = full-input
lasso_solver = sklearn
learning_rate = 0.01
lmbd = 0.1
max_update_iter = 1000
measurement_type = gaussian
mloss1_weight = 0.0
mloss2_weight = 1.0
model_types = ['lasso', 'vae']
momentum = 0.9
n_input = 784
noise_std = 0.1
not_lazy = True
num_input_images = 10
num_measurements = 100
num_random_restarts = 10
optimizer_type = adam
pretrained_model_dir = ./mnist_vae/models/mnist-vae/
print_stats = True
save_images = False
save_stats = False
sparsity = 1
superres_factor = 2
zprior_weight = 0.1

Extracting ./data/mnist/train-images-idx3-ubyte.gz
Traceback (most recent call last):
  File "./src/compressed_sensing.py", line 177, in <module>
    main(HPARAMS)
  File "./src/compressed_sensing.py", line 19, in main
    xs_dict = model_input(hparams)
  File "/home/gamkiu/csgm/src/mnist_input.py", line 56, in model_input
    mnist = input_data.read_data_sets('./data/mnist', one_hot=True)
  File "/home/gamkiu/anaconda3/envs/test/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 213, in read_data_sets
    train_images = extract_images(f)
  File "/home/gamkiu/anaconda3/envs/test/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 53, in extract_images
    magic = _read32(bytestream)
  File "/home/gamkiu/anaconda3/envs/test/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 35, in _read32
    return numpy.frombuffer(bytestream.read(4), dtype=dt)[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
(/home/gamkiu/anaconda3/envs/test) gamkiu@ubuntu:~/csgm$

**Comment by SummerAnAn** [comment]
Dear author， when I run the instruction./quick_scripts/mnist_reconstr.sh,I was  got the error like this ,how to solve it? Thank you very much!!

batch_size = 10
checkpoint_iter = 1
dataset = mnist
decay_lr = False
dloss1_weight = 0.0
dloss2_weight = 0.0
gif = False
gif_dir =
gif_iter = 1
image_matrix = 1
image_shape = (28, 28, 1)
inpaint_size = 1
input_path_pattern = ./data/celebAtest/*.jpg
input_type = full-input
lasso_solver = sklearn
learning_rate = 0.01
lmbd = 0.1
max_update_iter = 1000
measurement_type = gaussian
mloss1_weight = 0.0
mloss2_weight = 1.0
model_types = ['lasso', 'vae']
momentum = 0.9
n_input = 784
noise_std = 0.1
not_lazy = True
num_input_images = 10
num_measurements = 100
num_random_restarts = 10
optimizer_type = adam
pretrained_model_dir = ./mnist_vae/models/mnist-vae/
print_stats = True
save_images = False
save_stats = False
sparsity = 1
superres_factor = 2
zprior_weight = 0.1

WARNING:tensorflow:From C:\Users\39794\Desktop\csgm-master\src\mnist_input.py:56: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
WARNING:tensorflow:From C:\Users\39794\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please write your own downloading logic.
WARNING:tensorflow:From C:\Users\39794\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting ./data/mnist\train-images-idx3-ubyte.gz
WARNING:tensorflow:From C:\Users\39794\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting ./data/mnist\train-labels-idx1-ubyte.gz
WARNING:tensorflow:From C:\Users\39794\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:110: dense_to_one_hot (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting ./data/mnist\t10k-images-idx3-ubyte.gz
Extracting ./data/mnist\t10k-labels-idx1-ubyte.gz
WARNING:tensorflow:From C:\Users\39794\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
2020-01-03 18:41:41.522408: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "./src/compressed_sensing.py", line 177, in <module>
    main(HPARAMS)
  File "./src/compressed_sensing.py", line 21, in main
    estimators = utils.get_estimators(hparams)
  File "C:\Users\39794\Desktop\csgm-master\src\utils.py", line 98, in get_estimators
    estimators = {model_type: get_estimator(hparams, model_type) for model_type in hparams.model_types}
  File "C:\Users\39794\Desktop\csgm-master\src\utils.py", line 98, in <dictcomp>
    estimators = {model_type: get_estimator(hparams, model_type) for model_type in hparams.model_types}
  File "C:\Users\39794\Desktop\csgm-master\src\utils.py", line 72, in get_estimator
    estimator = mnist_estimators.vae_estimator(hparams)
  File "C:\Users\39794\Desktop\csgm-master\src\mnist_estimators.py", line 54, in vae_estimator
    z_batch, x_hat_batch, restore_path, restore_dict = mnist_model_def.vae_gen(hparams)
  File "C:\Users\39794\Desktop\csgm-master\src\mnist_model_def.py", line 28, in vae_gen
    return construct_gen(hparams, mnist_vae_model_def)
  File "C:\Users\39794\Desktop\csgm-master\src\mnist_model_def.py", line 18, in construct_gen
    _, x_hat = model_def.generator(model_hparams, z, 'gen', reuse=False)
  File "C:\Users\39794\Desktop\csgm-master\src\..\mnist_vae\src\model_def.py", line 50, in generator
    w1 = tf.get_variable('w1', initializer=utils.xavier_init(hparams.n_z, hparams.n_hidden_gener_1))
AttributeError: module 'utils' has no attribute 'xavier_init'
Some version information
python 3.5.2
tensorflow 1.8.0
